###What is NumPy?

- [NumPy](https://numpy.org/doc/stable/user/whatisnumpy.html#what-is-numpy) is the fundamental package for scientific computing in Python. 
- NumPy is a general-purpose array-processing Python library which provides handy methods/functions for working n-dimensional arrays. 
- [NumPy](https://www.geeksforgeeks.org/numpy-tutorial/) is a short form for “Numerical Python“. 
- It provides various computing tools such as comprehensive mathematical functions, and linear algebra routines.

###Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

###Why is NumPy Faster Than Lists?
- Memory Efficiency: Continuous memory blocks.
- Optimized C Implementation: Low-level, fast operations.
- Vectorized Operations: Efficient, no explicit loops needed.
- Data Type Homogeneity: Uniform data type, less memory.
- Broadcasting: Automatic, efficient operations across arrays.

###The Basics

####Load in NumPy (remember to pip install numpy first)

In [0]:
import numpy as np

####Creating Arrays
- The array object in NumPy is called `ndarray`.
- We can create a NumPy `ndarray` object by using the` array()` function.

In [0]:
# creation of array using array() method
a = [1, 2, 3]
a_array = np.array(a)
a_array

Out[24]: array([1, 2, 3])

In [0]:
# checking the datatype of array
a_array.dtype

Out[4]: dtype('int64')

In [0]:
b = [1, 2.0, 3]
f_array = np.array(b)
print(f_array)
print(f_array.dtype)

[1. 2. 3.]
float64


In [0]:
#specifying datatype while creation
f = [1, 2.0, 3]
f_array = np.array(f, dtype='int32')
print(f_array)
print(f_array.dtype)

[1 2 3]
int32


In [0]:
s = [1, 'Roish', "Zade"]
s_array = np.array(s)
print(s_array)
print(s_array.dtype)

['1' 'Roish' 'Zade']
<U21


In [0]:
# Get Dimension
a_array.ndim

Out[11]: 1

In [0]:
# 2D array
m = [[1,2,3],[4,5,6]]
m_array = np.array(m)
m_array

Out[14]: array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
m_array.ndim

Out[15]: 2

In [0]:
# Get Shape
a_array.shape

Out[21]: (3,)

In [0]:
m_array.shape

Out[17]: (2, 3)

In [0]:
# Get number of elements
print("a_array size:", a_array.size)
print("f_array size:", f_array.size)
print("m_array size:", m_array.size)

a_array size: 3
f_array size: 3
m_array size: 6


In [0]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array

Out[28]: array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
print("a_array size:", a_array.size)

a_array size: 9


In [0]:
threed_array = [[[1,2],[3,4]],[[5,6],[7,8]]]
threed_array = np.array(threed_array,dtype='int32')
threed_array

Out[31]: array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

In [0]:
print(threed_array.ndim)
print(threed_array.shape)
print(threed_array.size)

3
(2, 2, 2)
8


### Accessing/Changing specific elements, rows, columns, etc

In [0]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array

Out[34]: array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# access elements in array a_array [r,c]
print(a_array[2,2]) # 9
print(a_array[2,-1]) # 9
print(a_array[2,:]) # from last row all columns [7, 8, 9] 
print(a_array[:,1]) # from all rows second column 2, 5, 8
print(a_array[0:2,1:3]) # In first 2 rows last 2 columns ie, 2, 3 and 5, 6

9
9
[7 8 9]
[2 5 8]
[[2 3]
 [5 6]]


In [0]:
#assign a value/ change a value
print("before changiing: ", a_array)
a_array[2,2]=11
print("After changiing: ", a_array)

before changiing:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
After changiing:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 11]]


In [0]:
print("before changiing: ", a_array)
a_array[0:2,1:3]=[[9,10],[8,6]]
print("After changiing: ", a_array)

before changiing:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 11]]
After changiing:  [[ 1  9 10]
 [ 4  8  6]
 [ 7  8 11]]


In [0]:
d = [[[1,2],[3,4]],[[5,6],[7,8]]]
d_array = np.array(d,dtype='int32')
print(d_array.shape)
print(d_array)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [0]:
# accesing 3d array
print(d_array[0, 0, 0]) # first element
print(d_array[1, 1, 1])

1
8


###Initializing Different Types of Arrays

In [0]:
# All 0s matrix
p_array=np.zeros(5,dtype='int64')
print(p_array)
q_array = np.zeros((2,3))
print(q_array)

[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
r_array=np.zeros((5,5),dtype='int32')
print(r_array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [0]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

Out[51]: array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [0]:
np.ones((2,3),dtype='int32')

Out[53]: array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [0]:
# Any other number
np.full((2,2), 99)

Out[54]: array([[99, 99],
       [99, 99]])

In [0]:
# Any other number (full_like)
np.full_like(a, 4)

Out[55]: array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [0]:
# Random decimal numbers
np.random.rand(4,2)

Out[56]: array([[0.48459847, 0.39195716],
       [0.00803014, 0.87895849],
       [0.78214446, 0.79506195],
       [0.93180401, 0.33671455]])

In [0]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

Out[57]: array([[ 0,  7, -2],
       [ 5,  3, -3],
       [ 2, -1,  1]])

In [0]:
# The identity matrix
np.identity(3)

Out[59]: array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [0]:
# copy() will do shallow copy meaning only reference will be passed to a_array1
a_array= np.identity(3,dtype='int32')
a_array1=a_array.copy()
a_array1[0,0]=9

In [0]:
a_array

Out[62]: array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

###Mathmatics

In [0]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [0]:
print(a + 2)
print(a * 2)

[3 4 5 6]
[2 4 6 8]


In [0]:
a - 2

Out[65]: array([-1,  0,  1,  2])

In [0]:
a / 2

Out[66]: array([0.5, 1. , 1.5, 2. ])

In [0]:
b = np.array([1,0,1,0])

In [0]:
print("array a:", a)
print("array b:", b)

array a: [1 2 3 4]
array b: [1 0 1 0]


In [0]:
# adding 2 array's
a + b

Out[69]: array([2, 2, 4, 4])

In [0]:
a ** b

Out[75]: array([1, 1, 3, 1])

In [0]:
# Take the cos
np.cos(a)

Out[76]: array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [0]:
# Take the sin
np.sin(a)

- In a NumPy array, axis=0 represents the rows of the array.
- In a NumPy array, axis=1 represents the columns of the array.

In [0]:
#statistics
a = [[1,2,3],[4,5,6],[7,8,9]]
a_array = np.array(a)
a_array

Out[77]: array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.min(a_array)

Out[78]: 1

In [0]:
np.min(a_array,axis=0)

Out[79]: array([1, 2, 3])

In [0]:
np.min(a_array,axis=1)

Out[82]: array([1, 4, 7])

In [0]:
np.sum(a_array,axis=1)

Out[83]: array([ 6, 15, 24])

In [0]:
#rearrgrage
a = [[1,2,3],[4,5,6]]
a_array = np.array(a)
a_array.reshape((3,2))

Out[84]: array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a_array1= np.full((2,3),9,dtype='int32')
a_array2= np.full((2,3),5,dtype='int32')
print(a_array1)
print(a_array2)

[[9 9 9]
 [9 9 9]]
[[5 5 5]
 [5 5 5]]


In [0]:
#stacking multiple arrays
np.vstack((a_array1,a_array2))

Out[86]: array([[9, 9, 9],
       [9, 9, 9],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [0]:
np.hstack((a_array1,a_array2))

Out[87]: array([[9, 9, 9, 5, 5, 5],
       [9, 9, 9, 5, 5, 5]], dtype=int32)

In [0]:
# #create array from a file
# f = np.genfromtxt('readnp.txt',delimiter=',',dtype='int32')
# f

In [0]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

f = np.vstack([v1,v2,v1,v2])

In [0]:
f

Out[92]: array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
#advance indexing
f<5

Out[94]: array([[ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [0]:
f[f>5]

Out[95]: array([6, 7, 8, 6, 7, 8])

In [0]:
f[(f>5) & (f<10)]

Out[97]: array([6, 7, 8, 6, 7, 8])

In [0]:
f[(f>5) | (f<10)]

Out[96]: array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
f+2

Out[98]: array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])