### NumPy Assignment

#### 1. Create a numpy array of shape (3, 4) and assign random integers between 1 and 10 to every element.

In [1]:
import numpy as np

In [36]:
array1 = np.random.randint(1,11, size=(3,4))
array1

array([[ 2,  8,  6,  4],
       [ 4,  3,  3,  1],
       [10,  8,  5,  8]], dtype=int32)

##

#### 2. Find the maximum value in the array created in step 1.

In [37]:
max = np.max(array1)
max

np.int32(10)

#

#### 3. Calculate the mean value of each row in the array.

In [38]:
array_mean = np.mean(array1, axis=1)
array_mean

array([5.  , 2.75, 7.75])

#

#### 4. Reshape the array from step 1 into a shape of (2, 6).

In [39]:
reshaped_arr = np.reshape(array1, (2, 6))
print(reshaped_arr)

[[ 2  8  6  4  4  3]
 [ 3  1 10  8  5  8]]


#

#### 4. Multiply each element in the array by 2.

In [42]:
array1 * 2

array([[ 4, 16, 12,  8],
       [ 8,  6,  6,  2],
       [20, 16, 10, 16]], dtype=int32)

#

#### 6. Create a numpy array with values ranging from 0 to 9. Extract the odd numbers from the array.

In [43]:
array2 = np.arange(10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
odd_array = array2[array2 % 2 != 0]
odd_array

array([1, 3, 5, 7, 9])

#

#### 7. Create a 3x3 identity matrix using numpy.

In [47]:
identity_array = np.identity(3, dtype='int32')
identity_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

#

#### 8- Create a 5x5 array with random values and normalize it (subtract the mean and divide by the standard deviation of the array).

In [55]:
# Create a 5x5 array with random values
array3 = np.random.randn(5, 5)
array3

array([[ 1.06301336, -1.0449471 ,  0.28099075, -1.66560306,  0.89482955],
       [-0.36555517,  0.59994679, -1.63395355,  0.08858601,  0.12358898],
       [-2.01597258,  0.16569705,  1.74165112, -0.83330268,  0.90898414],
       [-0.55668049,  0.01644481, -0.36050448, -0.94667804, -0.30196762],
       [ 0.08810682,  1.45159537,  0.7455546 , -0.53419787,  0.38018142]])

In [58]:
# Calculate the mean and standard deviation
mean = np.mean(array3)
std = np.std(array3)

In [60]:
# Normalize the array
normalized_arr = (array3 - mean) / std
normalized_arr

array([[ 1.20284797, -1.03818864,  0.37145605, -1.6980268 ,  1.02404667],
       [-0.31590651,  0.71054788, -1.66437924,  0.16690474,  0.20411746],
       [-2.07051524,  0.24888383,  1.92432833, -0.81318305,  1.03909484],
       [-0.51909762,  0.09020924, -0.31053696, -0.93371582, -0.24830465],
       [ 0.1663953 ,  1.61596127,  0.86534794, -0.49519567,  0.47690865]])

#

#### 9. Perform element-wise multiplication between two arrays of the same shape.

In [65]:
# Create two arrays of the same shape
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [64]:
arr2 = np.array([[2, 3, 4],
                 [5, 6, 7]])


In [66]:
# Perform element-wise multiplication
result = arr1 * arr2
result

array([[ 2,  6, 12],
       [20, 30, 42]])

#

#### 10. Given an array of heights in centimeters, convert them to inches (1 inch = 2.54 cm).


In [68]:
heights_cm = np.array([160, 170, 180, 190])

In [69]:
heights_in = heights_cm / 2.54

heights_in

array([62.99212598, 66.92913386, 70.86614173, 74.80314961])

#

#### 11. Create a 1D array of numbers from 0 to 9. Replace all odd numbers with -1.

In [74]:
array4 = np.arange(10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
array4[array4 % 2 != 0] = -1
array4

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#

#### 12. Create a 2D array with random values and find the indices of the maximum and minimum values.

In [76]:
array5 = np.random.randn(3, 4)
array5

array([[ 0.09180223, -0.45104545,  1.33705521,  0.44741665],
       [-0.4028101 ,  1.66057775,  0.35182658, -0.11748583],
       [-1.57109113, -0.38862868, -0.81274649, -0.69482441]])